/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useLayoutEffect, useRef } from "react";
import { useGLTF, useAnimations } from "@react-three/drei";
import * as THREE from "three";

export default function AmbassadorMaterials({ scene, scale }) {
  const group = useRef();
  const { nodes, materials, animations } = useGLTF(
    "models/ambassador-minimal_04.glb"
  );
  const { actions } = useAnimations(animations, group);

  useLayoutEffect(() => {
    materials.headLampGlass = new THREE.MeshPhysicalMaterial();
    materials.headLampGlass.color.set("#FEF3C7");
    materials.headLampGlass.transparent = true;
    materials.headLampGlass.opacity = 0.2;
    materials.headLampGlass.roughness = 0;

    materials.glass.color.set("#000000");
    materials.glass.transparent = true;
    materials.glass.opacity = 0.9;
    materials.glass.roughness = 0;
  }, [materials]);
  return (
    <group ref={group} scale={scale}>
      <group name="Scene">
        <mesh
          name="wheel_arch_plastic"
          castShadow
          receiveShadow
          geometry={nodes.wheel_arch_plastic.geometry}
          material={materials["baked-metal-black"]}
        />
        <mesh
          name="glass"
          castShadow
          receiveShadow
          geometry={nodes.glass.geometry}
          material={materials.glass}
        />
        <mesh
          name="headlamp_lens"
          castShadow
          receiveShadow
          geometry={nodes.headlamp_lens.geometry}
          material={materials.headLampGlass}
        />
        <mesh
          name="indicator_lens"
          castShadow
          receiveShadow
          geometry={nodes.indicator_lens.geometry}
          material={materials["Glass-orange"]}
        />
        <mesh
          name="fog_lamp_cover"
          castShadow
          receiveShadow
          geometry={nodes.fog_lamp_cover.geometry}
          material={materials["bake-aux-lamp-cover"]}
        />
        <mesh
          name="tyre_01"
          castShadow
          receiveShadow
          geometry={nodes.tyre_01.geometry}
          material={materials["bake-tyre"]}
          position={[1.108, 0.438, 1.753]}
          rotation={[0.041, 0, 0]}
        />
        <mesh
          name="wheel_01"
          castShadow
          receiveShadow
          geometry={nodes.wheel_01.geometry}
          material={materials["bake-stained-chrome"]}
          position={[1.136, 0.439, 1.743]}
          rotation={[0.041, 0, 0]}
        />
        <group name="Armature" position={[1.026, 0.904, 1.17]} scale={0.393}>
          <primitive object={nodes.Bone} />
          <primitive object={nodes.Bone002} />
          <primitive object={nodes.Bone003} />
          <primitive object={nodes.Bone001} />
        </group>
        <mesh
          name="door_RR"
          castShadow
          receiveShadow
          geometry={nodes.door_RR.geometry}
          material={materials["baked-rusted-body"]}
          position={[1.16, 1.689, 1.31]}
          rotation={[-0.021, 0.606, 0.012]}
        />
        <mesh
          name="engine-block"
          castShadow
          receiveShadow
          geometry={nodes["engine-block"].geometry}
          material={materials["baked-rusty-metal"]}
          position={[0, 0.86, 2.238]}
          scale={0.176}
        />
        <mesh
          name="tail-lamp-mid"
          castShadow
          receiveShadow
          geometry={nodes["tail-lamp-mid"].geometry}
          material={materials.glass}
          position={[0, -0.001, 0.001]}
        />
        <mesh
          name="tail-lamp-top"
          castShadow
          receiveShadow
          geometry={nodes["tail-lamp-top"].geometry}
          material={materials["Glass-orange"]}
          position={[0, -0.001, 0.001]}
        />
        <mesh
          name="tail-lamp-bottom"
          castShadow
          receiveShadow
          geometry={nodes["tail-lamp-bottom"].geometry}
          material={materials["Glass-red"]}
          position={[0, -0.001, 0.001]}
        />
      </group>
    </group>
  );
}

useGLTF.preload("models/ambassador-minimal_04.glb");
