/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useEffect, useLayoutEffect, useRef } from "react";
import { useGLTF } from "@react-three/drei";
import * as THREE from "three";

export default function SuzukiSwiftMaterials({ scene }) {
  const { nodes, materials } = useGLTF(
    "models/Suzuki_Swift_mod_sketchfab_01.glb"
  );

  const ratioScale = Math.min(1.2, Math.max(0.5, window.innerWidth / 1920));

  useEffect(() => {
    // Create a new paint material
    materials.Carbon_fiber = new THREE.MeshPhysicalMaterial();
    materials.Carbon_fiber.color.set("#525252");
    materials.Carbon_fiber.roughness = 0;
    materials.Carbon_fiber.metalness = 0.5;

    materials.carpaint = new THREE.MeshPhysicalMaterial();
    materials.carpaint.color.set("#ffdf71");
    materials.carpaint.clearcoat = 1;
    materials.carpaint.clearcoatRoughness = 0;

    // Assign the specified values

    // Apply the new paint material to relevant meshes
    scene.traverse((child) => {
      if (child.isMesh && child.material.name === "carbon-bake.001") {
        child.material = materials.Carbon_fiber;
      }
    });
  }, [materials, scene]);

  useEffect(() => {
    console.log("materials", materials["Carpaint-white"].color);

    materials["Brake-disk"] = new THREE.MeshPhysicalMaterial();
    materials["Brake-disk"].color.set("#A3A3A3");
    materials["Brake-disk"].roughness = 0;
    materials["Brake-disk"].metalness = 0.5;

    materials["Carpaint-pink"].color.set("#ffdf71");
    materials["Carpaint-white"].color.set("#ffdf71");
    materials["Carpaint-white"].color.roughness = 0;
    materials["Carpaint-white"].color.metalness = 0.3;

    materials["Window border-gloss black"].color.set("#000000");
  }, [materials, scene]);
  return (
    <group>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Brake_disk.geometry}
        material={materials["Brake-disk"]}
        position={[0.683, 0.325, -1.348]}
        rotation={[0, 0, 0.052]}
        scale={1.173}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Bronze.geometry}
        material={materials.exhaust_tip}
        position={[0, -0.077, 0]}
      />
      <group position={[0, -0.077, 0]}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Vert005.geometry}
          material={materials["Glass-clear"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Vert005_1.geometry}
          material={materials["Glass-clear-bump.001"]}
        />
      </group>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Carbon_fiber.geometry}
        material={materials.Carbon_fiber}
        position={[0, -0.077, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Painted_body007.geometry}
        material={materials.carpaint}
        position={[0, -0.077, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Gloass_black.geometry}
        material={materials["Window border-gloss black"]}
        position={[0, -0.077, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Interior.geometry}
        material={materials["Interior - Black"]}
        position={[-0.383, 0.972, 0.758]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.red_glass_bump.geometry}
        material={materials["Glass-red-bump.001"]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Dark_rubber.geometry}
        material={materials["dark rubber"]}
        position={[0, -0.077, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.reflector.geometry}
        material={materials.Chrome}
        position={[0, -0.077, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Gloss_chrome.geometry}
        material={materials.Chrome}
        position={[0, -0.077, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.red_emission.geometry}
        material={materials["White emission.002"]}
        position={[0, -0.077, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Windshield.geometry}
        material={materials["Glass-tint.001"]}
        position={[0, -0.077, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.White_emission.geometry}
        material={materials["White emission"]}
        position={[0, -0.077, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Glass_with_bump.geometry}
        material={materials["Glass-clear-bump.002"]}
        position={[0, -0.077, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Chrome_rough.geometry}
        material={materials["Brake hub"]}
        position={[0, -0.077, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Glass_orange.geometry}
        material={materials["Glass-orange.001"]}
        position={[0, -0.077, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Gloass_paint.geometry}
        material={materials["Carpaint-pink"]}
        position={[0.683, 0.325, -1.348]}
        rotation={[0, 0, 0.052]}
        scale={1.173}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Tyre.geometry}
        material={materials["tyre new"]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Wheels.geometry}
        material={materials["Carpaint-white"]}
        position={[0.934, 0.319, 1.118]}
        rotation={[0, 0, 0.052]}
      />
    </group>
  );
}

useGLTF.preload("/Suzuki_Swift_mod_sketchfab_01.glb");
